dmaas jobs refactor

diff --git a/stages/14-director-gui-check/gui-dmaas-delete-minio b/stages/14-director-gui-check/gui-dmaas-delete-minio
--- a/stages/14-director-gui-check/gui-dmaas-delete-minio
+++ b/stages/14-director-gui-check/gui-dmaas-delete-minio
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-set -ex
+# set -ex
 
 
 ######################
@@ -35,7 +35,13 @@ git clone https://$username:$password@github.com/mayadata-io/gui-automation.git
 cd gui-automation
 
 bash scripts/dop-gui-stages/run-gui-tests.sh ${GROUP} ${GUID} ${URL} ${THREADS} eu-north-1
+STATUS=$(echo $?)
 
 #cp  $path/.awscluster2/config ~/.kube/config
 cd ../..
 bash utils/e2e-cr jobname:tcid-dir-dmaas-minio-delete jobphase:Completed
+
+# Exit if selenium jobs fails
+if [ "$STATUS" != "0" ]; then
+exit 1;
+fi
diff --git a/stages/14-director-gui-check/gui-dmaas-jiva-mysql b/stages/14-director-gui-check/gui-dmaas-jiva-mysql
--- a/stages/14-director-gui-check/gui-dmaas-jiva-mysql
+++ b/stages/14-director-gui-check/gui-dmaas-jiva-mysql
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-set -ex
+# set -ex
 
 
 ######################
@@ -83,12 +83,20 @@ cat ~/.dmaas/aws_cred ~/.dmaas/minio_cred >> cred.ini
 ######################
 ##   Running test  ##
 ######################
-python3.7 -m pip install -r requirements.txt
-#Running tests with dmaasJivaMysql marker
-python3.7 -m pytest -m dmaasJivaMysql --url $URL --environment remote --hub $grid -v --tests-per-worker 10 --html=./results/report.html
 
+bash scripts/dop-gui-stages/run-gui-tests.sh ${GROUP} ${GUID} ${URL} ${THREADS} eu-north-1
+
+STATUS=$(echo $?)
 
 cp  $path/.awscluster2/config ~/.kube/config
 cd ../..
 bash utils/e2e-cr jobname:tcid-dir-dmaas-schd-jiva-mysql-bucket jobphase:Completed
+
+# Exit if selenium jobs fails
+if [ "$STATUS" != "0" ]; then
+exit 1;
+fi
+
+# Delete mysql application
+kubectl delete -f $path/jiva-mysql/mysql-manifest/
 
